/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "cafecafe": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "email-tracking-handler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "email-tracking-queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "email-tracking-topic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "sst-email": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
